[internal]

; Phone dialing
exten => 100,1,Dial(PJSIP/100)
exten => 101,1,Dial(PJSIP/101)

; Call 500 → send urgent news to analog phone
exten => 500,1,Answer()
 same => n,Originate(PJSIP/101,app,Playback,urgent-news)
 same => n,Hangup()

; Call 600 → send weather alert to IP phone
exten => 600,1,Answer()
 same => n,Originate(PJSIP/100,app,Playback,weather-alert)
 same => n,Hangup()
